# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.4
  # - nightly
notifications:
  email: false

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Maker"); Pkg.test("Maker"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Maker")); Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl"); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("Maker")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'